---
title: "About"
---

About this site

I go by the name of Aanya Pandith, but I would rather be known as the person who is interested in everything. I am a skeptic, and i have a tendency called 'Philia sophia,' which literally translates to the love for wisdom. I believe in skepticism, one might feel that they are being interrogated, when I am around. I find talking to people and learning about their perspective extremely enriching, as it also helps me get different perspectives on any notion. I am currently interested in game theory, cognitive studies, epigenetic and heterotopia, apart from design and art.

The more I know, the more I want know. I more I want to know, the more deeper and wider my perspective becomes. This process of constant transformation and metamorphosis of the object of thought is awe inspiring. You realise, one can never be right or wrong, because the notion of right and wrong dosen't exist. only sides of each coin exist, which is subjective.

My professional expertise lies in creative coding. Yet my creative endeavors drive me for creating pathways to combine the various fields of art and design and creating a juncture where they all meet.
